version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app  # Dockerfile for your application
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - .:/app  # Mount the current directory into the container at /app
    command: sleep infinity  # Keep the application container running

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests  # Dockerfile for running tests
    volumes:
      - .:/app  # Mount the current directory into the container at /app
    depends_on:
      - app  # Ensure the application container is started first
    command: pytest  # Run pytest to execute the tests
